public class ExcDemo2 {
    /*
    An exception can be generated by one
    method and caught by another
    * */
    public static void main(String[] args) {
        try{
            ExcTest.genException();
        } catch (ArrayIndexOutOfBoundsException exc){
            // catch the exception
            System.out.println("Index-out-of-bound!");
        }
        System.out.println("After catch statement.");
    }
}