package take2;

/*
An exception can be generated by one method and caught by another
 */

class ExcTest1{
    // Generate an exception
    static void genException(){
        int [] nums = new int[4];
        System.out.println("Before exception is generated");

        // generate an index out of bound error
        nums[7] = 10;
        System.out.println("This won't be executed!");
    }
}

public class ExcDemo2 {
    public static void main(String[] args) {
        try{
            ExcTest1.genException(); // This is static method in the Class ExcTest we can call it without creating an instance of a class


        } catch (ArrayIndexOutOfBoundsException exc) {
            // catch the exception
            System.out.println("Index out of bound error");
        }
        System.out.println("After the catch statement!");
    }
}
